### ISSUE TITLE
bug: simulator keeps freezing 

### ISSUE THREAD

**Issue by virus-rpi** [DraqzzIQ/RISCV-Simulation#11]
![image](https://github.com/user-attachments/assets/39fd2687-748e-4725-8e3b-a8e0d1d96020)
when i executed the visible code it did nothing and after clicking the run button again it stopped responding.
this also happend with other scripts like the following one:
![image](https://github.com/user-attachments/assets/450abc6e-62ac-42e8-b199-7ed46d1f37df)
however both scripts did execute at least once at one time.

Platform: nyarch linux

**Comment by DraqzzIQ** [comment]
could you please verify #16 fixes this

**Comment by virus-rpi** [comment]
this fixed the freezes
